### ISSUE TITLE
Reference Paper

### ISSUE THREAD

**Issue by loretoparisi** [LazoCoder/Article-Summarizer#1]
Hi, is there any reference paper of this implementation or comparison with recent text summarization tools like the [OpenNTM](http://opennmt.net/Models/) ones etc.?
Thank you.

**Comment by LazoVelko** [comment]
There is no reference paper that I am aware of. This project was inspired by [SMMRY](http://smmry.com/about), which uses a very simplistic, old algorithm. The implementation doesn't use any fancy machine learning techniques so I doubt that it is as good as any of the newer tools.

**Comment by loretoparisi** [comment]
@LazoCoder thank you!
